//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Shib.XAF.Address.BusinessObjects.AddressModuleDataModel
{

    [MapInheritance(MapInheritanceType.ParentTable)]
    public partial class Country : PrimaryGeographicalUnit
    {
        [Association(@"RegionReferencesCountry")]
        public XPCollection<Region> Regions { get { return GetCollection<Region>(nameof(Regions)); } }
    }

}
