//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Shib.XAF.Address.BusinessObjects.AddressModuleDataModel
{

    public partial class Street : DevExpress.Persistent.BaseImpl.Address
    {
        Locality fLocality;
        [Association(@"StreetReferencesLocality")]
        public Locality Locality
        {
            get { return fLocality; }
            set { SetPropertyValue<Locality>(nameof(Locality), ref fLocality, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fHouseNumber;
        public string HouseNumber
        {
            get { return fHouseNumber; }
            set { SetPropertyValue<string>(nameof(HouseNumber), ref fHouseNumber, value); }
        }
    }

}
