apiVersion: v1
kind: Service
metadata:
  name: sunday-np-service-srv
spec:
  type: NodePort
  selector:
    app: sundayservice
  ports:
    - name: sundayservice
      protocol: TCP
      port: 80
      targetPort: 80