//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sunday.Module.BusinessObjects.SundayDataModel {

    public partial class BaseTree : DevExpress.Persistent.BaseImpl.BaseObject {
        BaseTree fParent;
        [Association(@"BaseTreeReferencesBaseTree")]
        public BaseTree Parent {
            get { return fParent; }
            set { SetPropertyValue<BaseTree>(nameof(Parent), ref fParent, value); }
        }
        string fName;
        public string Name {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        DateTime fCreateDate;
        public DateTime CreateDate {
            get { return fCreateDate; }
            set { SetPropertyValue<DateTime>(nameof(CreateDate), ref fCreateDate, value); }
        }
        [Association(@"BaseTreeReferencesBaseTree"), Aggregated]
        public XPCollection<BaseTree> BaseTreeCollection { get { return GetCollection<BaseTree>(nameof(BaseTreeCollection)); } }
    }

}
