//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sunday.Module.BusinessObjects.SundayDataModel
{

    public partial class CustomerOrder : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Customer fCustomer;
        [Association(@"CustomerOrderReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        [Size(700)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        Sunday.Module.BusinessObjects.Enums.CustomerOrderType fType;
        [ColumnDefaultValue(0)]
        public Sunday.Module.BusinessObjects.Enums.CustomerOrderType Type
        {
            get { return fType; }
            set { SetPropertyValue<Sunday.Module.BusinessObjects.Enums.CustomerOrderType>(nameof(Type), ref fType, value); }
        }
        DateTime fCreatedDate;
        public DateTime CreatedDate
        {
            get { return fCreatedDate; }
            set { SetPropertyValue<DateTime>(nameof(CreatedDate), ref fCreatedDate, value); }
        }
        string fCustomerRequirements;
        [Size(800)]
        public string CustomerRequirements
        {
            get { return fCustomerRequirements; }
            set { SetPropertyValue<string>(nameof(CustomerRequirements), ref fCustomerRequirements, value); }
        }
    }

}
