//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sunday.Module.BusinessObjects.SundayDataModel
{

    public partial class Department : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        [Association(@"WorkTypeReferencesDepartment")]
        public XPCollection<WorkType> WorkTypes { get { return GetCollection<WorkType>(nameof(WorkTypes)); } }
        [Association(@"DepartmentMemberReferencesDepartment"), Aggregated]
        public XPCollection<DepartmentMember> DepartmentMembers { get { return GetCollection<DepartmentMember>(nameof(DepartmentMembers)); } }
    }

}
