//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sunday.Module.BusinessObjects.SundayDataModel {

    public partial class ExampleData : XPObject {
        double fSum;
        public double Sum {
            get { return fSum; }
            set { SetPropertyValue<double>(nameof(Sum), ref fSum, value); }
        }
        DateTime fDate;
        public DateTime Date {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        Sunday.Module.BusinessObjects.Enums.ExampleEnum fType;
        public Sunday.Module.BusinessObjects.Enums.ExampleEnum Type {
            get { return fType; }
            set { SetPropertyValue<Sunday.Module.BusinessObjects.Enums.ExampleEnum>(nameof(Type), ref fType, value); }
        }
        string fName;
        public string Name {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
    }

}
