//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sunday.Module.BusinessObjects.SundayDataModel {

    public partial class Locality : DevExpress.Persistent.BaseImpl.BaseObject {
        string fName;
        public string Name {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        PrimaryGeographicalUnit fPGUnit;
        [Association(@"LocalityReferencesPrimaryGeographicalUnit")]
        public PrimaryGeographicalUnit PGUnit {
            get { return fPGUnit; }
            set { SetPropertyValue<PrimaryGeographicalUnit>(nameof(PGUnit), ref fPGUnit, value); }
        }
        [Association(@"StreetReferencesLocality")]
        public XPCollection<SundayStreet> Streets { get { return GetCollection<SundayStreet>(nameof(Streets)); } }
    }

}
