//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sunday.Module.BusinessObjects.SundayDataModel {

	public partial class Phone : XPObject {
		string fNumber;
		public string Number {
			get { return fNumber; }
			set { SetPropertyValue<string>(nameof(Number), ref fNumber, value); }
		}
		Sunday.Module.BusinessObjects.Enums.PhoneEnum fType;
		public Sunday.Module.BusinessObjects.Enums.PhoneEnum Type {
			get { return fType; }
			set { SetPropertyValue<Sunday.Module.BusinessObjects.Enums.PhoneEnum>(nameof(Type), ref fType, value); }
		}
	}

}
