//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sunday.Module.BusinessObjects.SundayDataModel
{

    public partial class PhysicalCustomer : Customer
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fSurname;
        public string Surname
        {
            get { return fSurname; }
            set { SetPropertyValue<string>(nameof(Surname), ref fSurname, value); }
        }
        string fMiddlename;
        public string Middlename
        {
            get { return fMiddlename; }
            set { SetPropertyValue<string>(nameof(Middlename), ref fMiddlename, value); }
        }
        string fVKLink;
        public string VKLink
        {
            get { return fVKLink; }
            set { SetPropertyValue<string>(nameof(VKLink), ref fVKLink, value); }
        }
        [PersistentAlias("[Surname] + ' ' + [Name] + ' ' + [Middlename]")]
        public string FullName
        {
            get { return (string)(EvaluateAlias(nameof(FullName))); }
        }
        [PersistentAlias("[Surname] + ' ' + Substring([Name], 0, 1) + '.' + Substring([Middlename], 0, 1)")]
        public string ShortName
        {
            get { return (string)(EvaluateAlias(nameof(ShortName))); }
        }
    }

}
