//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sunday.Module.BusinessObjects.SundayDataModel {

    public partial class SundayStreet : DevExpress.Persistent.BaseImpl.BaseObject {
        string fHouseNumber;
        public string HouseNumber {
            get { return fHouseNumber; }
            set { SetPropertyValue<string>(nameof(HouseNumber), ref fHouseNumber, value); }
        }
        string fName;
        public string Name {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        Locality fLocacity;
        [Association(@"StreetReferencesLocality")]
        public Locality Locacity {
            get { return fLocacity; }
            set { SetPropertyValue<Locality>(nameof(Locacity), ref fLocacity, value); }
        }
    }

}
