//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sunday.Common.SundayCommonDataModel
{

    public partial class State : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fName;
        public string StateName
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(StateName), ref fName, value); }
        }
        int fCode;
        public int StateCode
        {
            get { return fCode; }
            set { SetPropertyValue<int>(nameof(StateCode), ref fCode, value); }
        }
        [Association(@"StateReferencesState")]
        public XPCollection<State> OutStates { get { return GetCollection<State>(nameof(OutStates)); } }
        [Association(@"StateReferencesState")]
        public XPCollection<State> InputStates { get { return GetCollection<State>(nameof(InputStates)); } }
    }

}
